<a href="https://colab.research.google.com/github/isadoracfranco/ECO904/blob/main/Isadora_Atv_1_de_ECO904_Python_IA_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

Numpy é a biblioteca principal para computação científica em Python.

Ele fornece um objeto array multidimensional de alto desempenho e ferramentas para trabalhar com esses arrays.

In [ ]:
import numpy as np
np.__version__

'2.0.2'

## Matrizes

Um array numpy é uma grade de valores, todos do mesmo tipo, e é indexado por uma tupla de inteiros não negativos.

O número de dimensões é a classificação da matriz, a forma de uma matriz é uma tupla de inteiros que fornece o tamanho da matriz ao longo de cada dimensão.

In [ ]:
[1, 1.4, 'olÁ']

[1, 1.4, 'olÁ']

In [ ]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.shape

(3,)

In [ ]:
a.ndim

1

In [ ]:
a.size

3

In [ ]:
a.itemsize

8

In [ ]:
print(a[0], a[1], a[2])

1 2 3


In [ ]:
a[0] = 5
a

array([5, 2, 3])

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.shape

(2, 3)

In [ ]:
b.ndim

2

In [ ]:
print(b[0, 0], b[0, 1], b[1, 0])

1 2 4


# Funções para Criar Vetores

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((1,2))

array([[1., 1.]])

In [ ]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [ ]:
np.random.random((2,2))

array([[0.29459987, 0.59071791],
       [0.4668145 , 0.08627642]])

In [ ]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [ ]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

In [ ]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [ ]:
# matriz Vandermonde: útil na geração de modelos lineares de mínimos quadrados
np.vander((1, 2, 3, 4), 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

# Formatos

Arrays NumPy podem ser definidos usando sequências Python, como listas e tuplas.

Listas e tuplas são definidas usando [...]e (...), respectivamente. Listas e tuplas podem definir a criação do ndarray:

- uma lista de números criará uma matriz 1D,
- uma lista de listas criará uma matriz 2D,
- outras listas aninhadas criarão matrizes de dimensões mais altas.

Em geral, qualquer objeto de matriz é chamado de ndarray no NumPy.

In [ ]:
a1D = np.array([1, 2, 3, 4])
a1D

array([1, 2, 3, 4])

In [ ]:
a2D = np.array([[1, 2], [3, 4]])
a2D

array([[1, 2],
       [3, 4]])

In [ ]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Ao usar numpy.arraypara definir um novo array, você deve considerar o dtype dos elementos no array, que pode ser especificado explicitamente.

Esse recurso oferece mais controle sobre as estruturas de dados subjacentes e como os elementos são manipulados nas funções C/C++.

In [ ]:
np.array([[1,2],[3,4]], dtype=np.float64)

array([[1., 2.],
       [3., 4.]])

In [ ]:
np.array([[1.,2.],[3.,4.]], dtype=np.int64)

array([[1, 2],
       [3, 4]])

In [ ]:
np.array([[1, 2], [3, 4]], dtype=np.complex64)

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]], dtype=complex64)

## Estouro de Variáveis

In [ ]:
np.array([127, 128, 129], dtype=np.int8)

OverflowError: Python integer 128 out of bounds for int8

uint32 = inteiro 32 bits não sinalizado ( >= 0 )

int32 = inteiro 32 bits sinalizado

In [ ]:
a = np.array([2, 3, 4], dtype=np.uint32)
b = np.array([5, 6, 7], dtype=np.uint32)
a - b

array([4294967293, 4294967293, 4294967293], dtype=uint32)

In [ ]:
a - b.astype(np.int32)

array([-3, -3, -3])

## Ponto flutuante IEEE 754

Valores especiais definidos em numpy: nan, inf

In [ ]:
np.nan == np.nan

False

In [ ]:
np.isnan(np.nan)

np.True_

In [ ]:
np.array([1., 0., np.nan, 3., np.inf])

array([ 1.,  0., nan,  3., inf])

In [ ]:
d = np.array([1,1,1])/0

<ipython-input-45-81699a001d75>:1: RuntimeWarning: divide by zero encountered in divide
  d = np.array([1,1,1])/0


In [ ]:
d

array([inf, inf, inf])

# Indexação

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [ ]:
a[:, 1]

array([ 2,  6, 10])

In [ ]:
a[:, 1:2]

array([[ 2],
       [ 6],
       [10]])

In [ ]:
b = np.array([0, 2, 1])
a[np.arange(3), b]

array([ 1,  7, 10])

In [ ]:
a[np.arange(3), b] += 10
a

array([[11,  2,  3,  4],
       [ 5,  6, 17,  8],
       [ 9, 20, 11, 12]])

In [ ]:
a > 10

array([[ True, False, False, False],
       [False, False,  True, False],
       [False,  True,  True,  True]])

In [ ]:
a[ a > 10 ]

array([11, 17, 20, 11, 12])

# Operações

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
y = np.array([[5,6],[7,8]], dtype=np.float64)
y

array([[5., 6.],
       [7., 8.]])

## Entre Vetores

In [ ]:
x + y

array([[ 6.,  8.],
       [10., 12.]])

In [ ]:
np.add(x, y)

array([[ 6.,  8.],
       [10., 12.]])

In [ ]:
x - y # np.subtract(x, y)

array([[-4., -4.],
       [-4., -4.]])

In [ ]:
x * y # np.multiply(x, y)

array([[ 5., 12.],
       [21., 32.]])

In [ ]:
x / y # np.divide(x, y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

## Cáculo Escalar

In [ ]:
x + 2

array([[3., 4.],
       [5., 6.]])

In [ ]:
x * 3

array([[ 3.,  6.],
       [ 9., 12.]])

In [ ]:
x / 4

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

## Produto Interno

<img src="https://lhmet.github.io/adar-ebook/images/multilicacaoMatricial.png">

In [ ]:
A = np.array([[2,3],[1,0],[4,5]])
B = np.array([[3,1],[2,4]])
np.dot(A,B)

array([[12, 14],
       [ 3,  1],
       [22, 24]])

Outros exemplos:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

v.dot(w) # np.dot(v, w)

np.int64(219)

In [ ]:
x.dot(v) # np.dot(x, v)

array([29, 67])

In [ ]:
x.dot(y)

array([[19, 22],
       [43, 50]])

## Outras Operações

In [ ]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [ ]:
np.sum(a) # a.sum()

np.float64(4.8595784)

In [ ]:
a.max()

np.float64(0.82485143)

In [ ]:
a.min()

np.float64(0.05093587)

In [ ]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [ ]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [ ]:
a.T

array([[0.45053314, 0.54627315, 0.12697628],
       [0.17296777, 0.05093587, 0.82485143],
       [0.34376245, 0.40067661, 0.26590556],
       [0.5510652 , 0.55645993, 0.56917101]])

In [ ]:
np.empty_like(a)

array([[0.45053314, 0.54627315, 0.12697628, 0.17296777],
       [0.05093587, 0.82485143, 0.34376245, 0.40067661],
       [0.26590556, 0.5510652 , 0.55645993, 0.56917101]])

In [ ]:
np.tile(a, (4, 1))

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101],
       [0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101],
       [0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101],
       [0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [ ]:
np.reshape(a, (12, 1))

array([[0.45053314],
       [0.17296777],
       [0.34376245],
       [0.5510652 ],
       [0.54627315],
       [0.05093587],
       [0.40067661],
       [0.55645993],
       [0.12697628],
       [0.82485143],
       [0.26590556],
       [0.56917101]])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

a[np.newaxis, :]

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
a[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
np.unique([1,1,2,2,3,3,4,4,5,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.flip([1,1,2,2,3,3,4,4,5,5])

array([5, 5, 4, 4, 3, 3, 2, 2, 1, 1])

In [ ]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.flatten()

array([0.45053314, 0.17296777, 0.34376245, 0.5510652 , 0.54627315,
       0.05093587, 0.40067661, 0.55645993, 0.12697628, 0.82485143,
       0.26590556, 0.56917101])

In [ ]:
b = a.ravel()
b[4] = 0.9999
a

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.9999    , 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [ ]:
d = np.array([1., 0., np.nan, 3.])

## Fórmulas Matemáticas

<img src="https://numpy.org/doc/stable/_images/np_MSE_formula.png">

<img src="https://numpy.org/doc/stable/_images/np_MSE_implementation.png">

### Atividade

Calcule o MSE (Erro médio quadrático) dos vetores gerados abaixo:

In [ ]:
np.random.seed(int(input('Forneça sua matrícula: ')))

real = np.random.random(100)
previsto = np.random.random(100)

Forneça sua matrícula: 2023004855


In [ ]:
# implemente o erro aqui
erro = np.mean(np.square(previsto - real))
print("MSE:", erro)

MSE: 0.17470358975410516


Identifique qual cálculo é mais rápido dotList vs dotNumpy.

Rode 1000 vezes cada um para comparar o tempo com o comando "%%time".

In [ ]:
a = np.random.randn(1000)
b = np.random.randn(1000)

A = list(a)
B = list(b)

def dotList():
    dot = 0
    for i in range(len(A)):
        dot += A[i]*B[i]
    return dot

def dotNumpy():
    return np.dot(a,b)

In [ ]:
%%time
# implemente aqui
for _ in range(1000):
    dotList()


CPU times: user 165 ms, sys: 0 ns, total: 165 ms
Wall time: 173 ms


In [ ]:
%%time
for _ in range(1000):
    dotNumpy()

CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 3.76 ms


# Manipulação de Arquivos

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
np.save('arquivo', a)

np.load('arquivo.npy')

array([1, 2, 3, 4, 5, 6])

In [ ]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.savetxt('arquivo.txt', b)

np.loadtxt('arquivo.txt')

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
c = np.array([[-2.58289208,  0.43014843, -1.24082018, 1.59572603],
              [ 0.99027828, 1.17150989,  0.94125714, -0.14692469],
              [ 0.76989341,  0.81299683, -0.95068423, 0.11769564],
              [ 0.20484034,  0.34784527,  1.96979195, 0.51992837]])
np.savetxt('colunas.txt', c)

In [ ]:
%%writefile sistemas.txt
0 1 2 3 4 5 6 7 8 9
10 11 12 13 14 15 16 17 18 19
20 21 22 23 24 25 26 27 28 29

Writing sistemas.txt


In [ ]:
np.loadtxt('sistemas.txt').astype(int)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# Sistemas Lineares

https://numpy.org/doc/stable/reference/routines.linalg.html

In [ ]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])

x = np.linalg.solve(a, b)
x

array([-1.,  1.])

Confirmando:

In [ ]:
np.dot(a, x)

array([1., 2.])

In [ ]:
np.allclose(np.dot(a, x), b)

True

## Autovalores e Autovetores

In [ ]:
a = np.array([[1,2], [3,4]])
autovalores, autovetores = np.linalg.eig(a)
print('autovalores:',autovalores,'\n')
print('autovetores:',autovetores)

autovalores: [-0.37228132  5.37228132] 

autovetores: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## Atividade

Implemente a solução do sistema abaixo:

<img src="https://escolaeducacao.com.br/wp-content/uploads/2020/04/sistema-exemplo1-300x151.jpg">

In [ ]:
import numpy as np

# matriz dos coeficientes (lado esquerdo das equações)
A = np.array([
    [2, 1, -2],
    [3, 2, 2],
    [5, 4, 3]
])

# vetor dos resultados (lado direito das equações)
b = np.array([10, 1, 4])

# resolvendo o sistema Ax = b
solucao = np.linalg.solve(A, b)

print("Solução (x, y, z):", solucao)

Solução (x, y, z): [ 1.  2. -3.]
